# Run the project's test suite
name: Tests

on: [pull_request, push]

jobs:
  test:
    name: Test ${{ matrix.os }} Python ${{ matrix.python-version }} conda=${{ matrix.use-conda }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    env:
      PYTHON_VERSION: ${{ matrix.python-version }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.7', '3.10']
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Install Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
           auto-update-conda: true
           channels: conda-forge
           python-version: ${{ matrix.python-version }}
      - name: Install env-manager and test dependencies
        run: |
        python -m pip install -e .[test]
      - name: Run tests
        run: |
        pytest --cov=env_manager -vv